### ISSUE TITLE
Put CMD into ENTRYPOINT

### ISSUE THREAD

**Issue by Flamefire** [ahrnbom/strudl#8]
According to the [docu](https://docs.docker.com/engine/reference/builder/#cmd)

> If the user specifies arguments to docker run then they will override the default specified in CMD.

This makes the construct used in https://github.com/ahrnbom/strudl/blob/master/Dockerfile#L69 unsuitable as it does not allow to pass arguments (such as `--port`) to the server.py

Solution: Remove CMD section and add to ENTRYPOINT

**Comment by ahrnbom** [comment]
I don't think this is a good idea. I tested with ENTRYPOINT `[ "/usr/bin/tini", "--", "python3", "server.py" ]`, which does work to some extent, but prevents the use of other commands, like `py.test -v` och `bash` which we use frequently. We don't always want to start the server; the CMD is just a default command to get people started. And overwriting ENTRYPOINT at runtime is not something I think we should be doing. 

If you want to pass an argument, you can do it like this: `nvidia-docker run -ti ahrnbom/strudl python3 server.py --port=1234`

Maybe CMD should instead provide some helpful guidance, like displaying command line usage, instead of just starting the server at the default port? I still think running the server with default settings is a useful default command.

**Comment by Flamefire** [comment]
True, if you want to support other commands, then yes. I agree that this might be useful
